default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  port: 5432
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: sample_development

test:
  <<: *default
  database: sample_test
